version: "3.9"
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "onLine-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    container_name: onLine